### ISSUE TITLE
arm64 CI build failure

### ISSUE THREAD

**Issue by nightlark** [GMLC-TDC/netif#22]
While the status from the CI service is that the build passed, it is actually failing due to an error when running the build, as can be seen in the latest build: https://cloud.drone.io/GMLC-TDC/netif/91/1/3

After a bit of digging, I think the solution for now is to pin the image used for the build step to `alpine:3.13` (preferred if it works) or if that fails `alpine:3.12`.

The way to get it working with newer versions of alpine again likely involves the CI provider updating the version of Docker they are running (this problem affects other users as well: https://discourse.drone.io/t/cloud-alpine-3-14-does-not-work/9992).

```
+ cmake -DENABLE_NETIF_TESTS=ON ..
-- The C compiler identification is GNU 11.2.1
-- The CXX compiler identification is GNU 11.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - broken
CMake Error at /usr/share/cmake/Modules/CMakeTestCCompiler.cmake:69 (message):
  The C compiler

    "/usr/bin/cc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /drone/src/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):/usr/bin/make -f Makefile cmTC_409bd/fast && /usr/bin/make  -f CMakeFiles/cmTC_409bd.dir/build.make CMakeFiles/cmTC_409bd.dir/build
    make: /usr/bin/make: Operation not permitted
    make: *** [Makefile:127: cmTC_409bd/fast] Error 127
    
  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:11 (project)

-- Configuring incomplete, errors occurred!
```

**Comment by nightlark** [comment]
Alright, let me know if you need any additional info.

**Comment by 20RitikSingh** [comment]
sir this is a new domain for me can you provide with some resources to begin with?

**Comment by nightlark** [comment]
@20RitikSingh just wanted to check how things are going -- is there anything in particular you're stuck on?

**Comment by nightlark** [comment]
Drone Cloud became unreliable for ARM64 builds. Those have now been moved to Cirrus CI.
