### ISSUE TITLE
Missing 'inline' causes "multiple definition" errors when using NetIF.hpp from multiple TUs

### ISSUE THREAD

**Issue by EelisVP** [GMLC-TDC/netif#62]
The following functions defined in NetIF.hpp are missing `inline`:

- `getInterfaceAddresses`
- `getInterfaceAddressesV4`
- `getInterfaceAddressesV6`
- `getInterfaceAddressesAll`

As soon as you use NetIF.hpp from multiple TUs, this results in "multiple definition of ..." errors.

**Comment by nightlark** [comment]
Thanks! This should be resolved in the latest commit to main now.
